import Marq from "@/components/Marquee";
import { DevLinkProvider, Navbar, Footer } from "@/devlink";

import "./globals.css";
import "@/devlink/global.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DevLinkProvider>
          <Navbar navHome={{ href: '/' }} navDirectory={{ href: '/directory' }} navLogin={{ href: '/login' }} />
          {children}
          <Marq />
          <Footer
            footerInsta={{ href: 'https://www.instagram.com/greaterfwbuildersassociation/' }}
            footerFacebook={{ href: 'https://www.facebook.com/GFWBA' }}
            footerX={{ href: 'https://twitter.com/i/flow/login?redirect_after_login=%2FFWBuildersAssoc' }}
            footerLinkedIn={{ href: 'https://www.linkedin.com/company/greater-fort-worth-builders-association/' }}
          />
        </DevLinkProvider>
      </body>
    </html>
  );
}
