import Marq from "@/components/Marquee";
import { DevLinkProvider, Navbar, Footer } from "@/devlink";

import "./globals.css";
import "@/devlink/global.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DevLinkProvider>
          <Navbar
            navHome={{ href: '/' }}
            navDirectory={{ href: '/directory' }}
            navLogin={{ href: '/login' }}
            navMembership={{ href: '/membership' }}
          />
          {children}
          <Marq />
          <Footer
            footerInsta={{ href: 'https://www.instagram.com/greaterfwbuildersassociation/', target: '_blank' }}
            footerFacebook={{ href: 'https://www.facebook.com/GFWBA', target: '_blank' }}
            footerX={{ href: 'https://twitter.com/i/flow/login?redirect_after_login=%2FFWBuildersAssoc', target: '_blank' }}
            footerLinkedIn={{ href: 'https://www.linkedin.com/company/greater-fort-worth-builders-association/', target: '_blank' }}
          />
        </DevLinkProvider>
      </body>
    </html>
  );
}
