import Head from "next/head";
import { DevLinkProvider } from "@/devlink";
import { Navbar } from "@/devlink/Navbar";

import "./globals.css";
import "@/devlink/global.css";

<Head>
  <link
    rel="stylesheet"
    href={`https://use.typekit.net/wso4vxx.css`}
  />
</Head>


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DevLinkProvider>
          <Navbar />
          {children}
        </DevLinkProvider>
      </body>
    </html>
  );
}
